nhl = {'Tampa Bay Lightning':'Tampa Bay Area', 
            'Boston Bruins':'Boston', 
            'Toronto Maple Leafs':'Toronto', 
            'Florida Panthers':'Miami–Fort Lauderdale', 
            'Detroit Red Wings':'Detroit', 
            'Montreal Canadiens':'Montreal', 
            'Ottawa Senators':'Ottawa', 
            'Buffalo Sabres':'Buffalo',
            'Washington Capitals':'Washington, D.C.', 
            'Pittsburgh Penguins':'Pittsburgh', 
            'Philadelphia Flyers':'Philadelphia', 
            'Columbus Blue Jackets':'Columbus', 
            'New Jersey Devils':'New York City',
            'Carolina Hurricanes':'Raleigh',
            'New York Islanders':'New York City',
            'New York Rangers':'New York City',
            'Nashville Predators':'Nashville',
            'Winnipeg Jets':'Winnipeg',
            'Minnesota Wild':'Minneapolis–Saint Paul',
            'Colorado Avalanche':'Denver',
            'St. Louis Blues':'St. Louis',
            'Dallas Stars':'Dallas–Fort Worth',
            'Chicago Blackhawks':'Chicago',
            'Vegas Golden Knights':'Las Vegas',
            'Anaheim Ducks':'Los Angeles',
            'San Jose Sharks':'San Francisco Bay Area',
            'Los Angeles Kings':'Los Angeles',
            'Calgary Flames':'Calgary',
            'Edmonton Oilers':'Edmonton',
            'Vancouver Canucks':'Vancouver',
            'Arizona Coyotes':'Phoenix'}


nba = {'Toronto Raptors':'Toronto',
                'Boston Celtics':'Boston',
                'Philadelphia 76ers':'Philadelphia',
                'Cleveland Cavaliers':'Cleveland',
                'Indiana Pacers':'Indianapolis',
                'Miami Heat':'Miami–Fort Lauderdale',
                'Milwaukee Bucks':'Milwaukee',
                'Washington Wizards':'Washington, D.C.',
                'Detroit Pistons':'Detroit',
                'Charlotte Hornets':'Charlotte',
                'New York Knicks':'New York City',
                'Brooklyn Nets':'New York City',
                'Chicago Bulls':'Chicago',
                'Orlando Magic':'Orlando',
                'Atlanta Hawks':'Atlanta',
                'Houston Rockets':'Houston',
                'Golden State Warriors':'San Francisco Bay Area',
                'Portland Trail Blazers':'Portland',
                'Oklahoma City Thunder':'Oklahoma City',
                'Utah Jazz':'Salt Lake City',
                'New Orleans Pelicans':'New Orleans',
                'San Antonio Spurs':'San Antonio',
                'Minnesota Timberwolves':'Minneapolis–Saint Paul',
                'Denver Nuggets':'Denver',
                'Los Angeles Clippers':'Los Angeles',
                'Los Angeles Lakers':'Los Angeles',
                'Sacramento Kings':'Sacramento',
                'Dallas Mavericks':'Dallas–Fort Worth',
                'Memphis Grizzlies':'Memphis',
                'Phoenix Suns':'Phoenix'}

mlb = {'Boston Red Sox':'Boston',
                'New York Yankees':'New York City',
                'Tampa Bay Rays':'Tampa Bay Area',
                'Toronto Blue Jays':'Toronto',
                'Baltimore Orioles':'Baltimore',
                'Cleveland Indians':'Cleveland',
                'Minnesota Twins':'Minneapolis–Saint Paul',
                'Detroit Tigers':'Detroit',
                'Chicago White Sox':'Chicago',
                'Kansas City Royals':'Kansas City',
                'Houston Astros':'Houston',
                'Oakland Athletics':'San Francisco Bay Area',
                'Seattle Mariners':'Seattle',
                'Los Angeles Angels':'Los Angeles',
                'Texas Rangers':'Dallas–Fort Worth',
                'Atlanta Braves':'Atlanta',
                'Washington Nationals':'Washington, D.C.',
                'Philadelphia Phillies':'Philadelphia',
                'New York Mets':'New York City',
                'Miami Marlins':'Miami–Fort Lauderdale',
                'Milwaukee Brewers':'Milwaukee',
                'Chicago Cubs':'Chicago',
                'St. Louis Cardinals':'St. Louis',
                'Pittsburgh Pirates':'Pittsburgh',
                'Cincinnati Reds':'Cincinnati',
                'Los Angeles Dodgers':'Los Angeles',
                'Colorado Rockies':'Denver',
                'Arizona Diamondbacks':'Phoenix',
                'San Francisco Giants':'San Francisco Bay Area',
                'San Diego Padres':'San Diego'}

nfl = {'New England Patriots':'Boston',
                'Miami Dolphins':'Miami–Fort Lauderdale',
                'Buffalo Bills':'Buffalo',
                'New York Jets':'New York City',
                'Baltimore Ravens':'Baltimore',
                'Pittsburgh Steelers':'Pittsburgh',
                'Cleveland Browns':'Cleveland',
                'Cincinnati Bengals':'Cincinnati',
                'Houston Texans':'Houston',
                'Indianapolis Colts':'Indianapolis',
                'Tennessee Titans':'Nashville',
                'Jacksonville Jaguars':'Jacksonville',
                'Kansas City Chiefs':'Kansas City',
                'Los Angeles Chargers':'Los Angeles',
                'Denver Broncos':'Denver',
                'Oakland Raiders':'San Francisco Bay Area',
                'Dallas Cowboys':'Dallas–Fort Worth',
                'Philadelphia Eagles':'Philadelphia',
                'Washington Redskins':'Washington, D.C.',
                'New York Giants':'New York City',
                'Chicago Bears':'Chicago',
                'Minnesota Vikings':'Minneapolis–Saint Paul',
                'Green Bay Packers':'Green Bay',
                'Detroit Lions':'Detroit',
                'New Orleans Saints':'New Orleans',
                'Carolina Panthers':'Charlotte',
                'Atlanta Falcons':'Atlanta',
                'Tampa Bay Buccaneers':'Tampa Bay Area',
                'Los Angeles Rams':'Los Angeles',
                'Seattle Seahawks':'Seattle',
                'San Francisco 49ers':'San Francisco Bay Area',
                'Arizona Cardinals':'Phoenix'}

lat_lon = {
            'Atlanta':[33.75,-84.39],
            'Baltimore':[39.30,-76.61],
            'Boston':[42.36,-71.06],
            'Buffalo':[42.88,-78.88],
            'Calgary':[51.05,-114.07],
            'Charlotte':[35.23,-80.84],
            'Chicago':[41.88,-87.62],
            'Cincinnati':[39.10,-84.51],
            'Cleveland':[41.51,-81.68],
            'Columbus':[39.98,-82.98],
            'Dallas–Fort Worth':[32.90,-97.04],
            'Denver':[39.74,-104.99],
            'Detroit':[42.33,-83.05],
            'Edmonton':[53.63,-113.32],
            'Green Bay':[44.51,-88.02],
            'Houston':[29.75,-95.36],
            'Indianapolis':[39.79,-86.15],
            'Jacksonville':[30.33,-81.66],
            'Kansas City':[39.10,-94.58],
            'Las Vegas':[36.11,-115.17],
            'Los Angeles':[34.05,-118.24],
            'Memphis':[35.18,-89.97],
            'Miami–Fort Lauderdale':[26.12,-80,14],
            'Milwaukee':[43.04,-87.91],
            'Minneapolis–Saint Paul':[44.95,-93.09],
            'Montreal':[45.51,-73.56],
            'Nashville':[36.17,-86.77],
            'New Orleans':[29.95,-90.07],
            'New York City':[40.73,-73.94],
            'Oklahoma City':[35.48,-97.51],
            'Orlando':[28.54,-81.38],
            'Ottawa':[45.42,-75.70], 
            'Philadelphia':[39.95,-75.17],
            'Phoenix':[33.44,-112.07], 
            'Pittsburgh':[40.44,-80.00], 
            'Portland':[45.52,-122.68],
            'Raleigh':[35.79,-78.64],
            'Sacramento':[38.58,-121.48],
            'Salt Lake City':[40.76,-111.88],
            'San Antonio':[29.42,-98.49],
            'San Diego':[32.72,-117.16],
            'San Francisco Bay Area':[37.77,-122.43],
            'Seattle':[47.61,-122.34],
            'St. Louis':[38.63,-90.20],
            'Tampa Bay Area':[27.98,-82.54],  
            'Toronto':[43.65,-79.35],
            'Vancouver':[49.25,-123.12],
            'Washington, D.C.':[38.90,-77.04],
            'Winnipeg':[49.90,-97.14]
        }